In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
import time

In [2]:
service = Service ('../Code/chromedriver-win64/chromedriver.exe')

In [3]:
id = pd.read_excel("../Code/Unseen Dataset for NN.xlsx",usecols=['IMDb ID'])
id.head()

     IMDb ID
0  tt0087803
1  tt0065622
2  tt0085694
3  tt0118528
4  tt0059125

In [4]:
def getpage (url):
    driver = webdriver.Chrome(service=service)
    driver.get(url)
    page_height = driver.execute_script("return document.body.scrollHeight;")
    print(page_height)
    driver.execute_script(f'window.scrollTo(0,{page_height}/3.3)')
    time.sleep(5)
    html = driver.page_source
    driver.quit()
    return html

In [5]:
def extractingdetails(html):
    soup = BeautifulSoup(html,'lxml')
    genre = []
    title = soup.find('span', class_='hero__primary-text').text
    description = soup.find('span',{
        'class':'sc-2d37a7c7-2 PeLXr',
        'data-testid' :"plot-xl"
    }).text
    block = soup.find('section', {
    'cel_widget_id': "StaticFeature_Storyline",
    'class': "ipc-page-section ipc-page-section--base celwidget",
    'data-cel-widget': "StaticFeature_Storyline",
    'data-testid': "Storyline"
})
    if block:
        story = block.find('div',{'class' : 'ipc-html-content-inner-div'}).text
        story = description+story
        li_tags = block.find_all('a', {'class': 'ipc-metadata-list-item__list-content-item ipc-metadata-list-item__list-content-item--link'})
        for li_tag in li_tags:
            genre.append(li_tag.text)
    return title, genre, story

In [6]:
data = []
for i, row in id.iterrows():
    imdb_id = row['IMDb ID']
    url = f"https://www.imdb.com/title/{imdb_id}/?ref_=fn_al_tt_1"
    try:
        print("Trying to get details...")
        html = getpage(url)
        title, genre, storyline = extractingdetails(html)
        data.append({'IMBb ID': imdb_id, 'Title': title, 'Storyline': storyline, 'Genres':genre})
        print(f'Details of {title} scrapped successfully!')
    except Exception as e:
        print("Error occurred!")
        print(f'Error: {e}')

Trying to get details...
11556
Details of 1984 scrapped successfully!
Trying to get details...
10968
Details of The Decameron scrapped successfully!
Trying to get details...
10702
Details of The House on Sorority Row scrapped successfully!
Trying to get details...
10473
Details of 12 Angry Men scrapped successfully!
Trying to get details...
10741
Details of Dr. Terror's House of Horrors scrapped successfully!
Trying to get details...
9691
Details of No One Would Tell scrapped successfully!
Trying to get details...
11351
Details of The Vampire Lovers scrapped successfully!
Trying to get details...
10465
Details of Arabian Nights scrapped successfully!
Trying to get details...
10784
Details of Heaven's Gate scrapped successfully!
Trying to get details...
10857
Details of The Garden of the Finzi-Continis scrapped successfully!
Trying to get details...
11083
Details of Zulu scrapped successfully!
Trying to get details...
10846
Details of Broken Arrow scrapped successfully!
Trying to get details...
10800
Details of Supernova scrapped successfully!
Trying to get details...
10675
Details of Troll 2 scrapped successfully!
Trying to get details...
11105
Details of Stalag 17 scrapped successfully!
Trying to get details...
10637
Details of Charro! scrapped successfully!
Trying to get details...
10876
Details of Shivers scrapped successfully!
Trying to get details...
10934
Details of Red River scrapped successfully!
Trying to get details...
8913
Details of The Gunfighter scrapped successfully!
Trying to get details...
11132
Details of The Bride Wore Black scrapped successfully!
Trying to get details...
10933
Details of Romance & Cigarettes scrapped successfully!
Trying to get details...
9635
Details of Day of the Outlaw scrapped successfully!
Trying to get details...
10661
Details of La Cage aux Folles scrapped successfully!
Trying to get details...
11130
Details of The Masque of the Red Death scrapped successfully!
Trying to get details...
10347
Details of X-Ray scrapped successfully!

In [7]:
dataframe = pd.DataFrame(data)
dataframe

,IMBb ID,Title,Storyline,Genres
0,tt0087803,1984,Based on George Orwell's novel. In a totalitar...,"[Drama, Sci-Fi]"
1,tt0065622,The Decameron,An adaptation of nine stories from Boccaccio's...,"[Comedy, Drama, History, Romance]"
2,tt0085694,The House on Sorority Row,After a seemingly innocent prank goes horribly...,"[Horror, Mystery, Thriller]"
3,tt0118528,12 Angry Men,Twelve men must decide the fate of one when on...,"[Crime, Drama]"
4,tt0059125,Dr. Terror's House of Horrors,"Aboard a British train, mysterious fortune tel...",[Horror]
5,tt0117191,No One Would Tell,A shy high school student's seemingly perfect ...,"[Biography, Crime, Drama, Sport, Thriller]"
6,tt0066518,The Vampire Lovers,Seductive vampire Carmilla Karnstein and her f...,[Horror]
7,tt0071502,Arabian Nights,"In ancient Arabia, a beautiful slave girl choo...","[Comedy, Drama, Fantasy, History, Romance]"
8,tt0080855,Heaven's Gate,"During the Johnson County War in 1890 Wyoming,...","[Adventure, Drama, Western]"
9,tt0065777,The Garden of the Finzi-Continis,"The story of the Finzi-Continis, a noble famil...","[Drama, History, War]"
10,tt0058777,Zulu,Outnumbered British soldiers do battle with Zu...,"[Drama, History, War]"
11,tt0115759,Broken Arrow,Terrorists steal nuclear warheads from the U.S...,"[Action, Adventure, Thriller]"
12,tt0134983,Supernova,A deep space rescue and recovery spaceship wit...,"[Horror, Sci-Fi, Thriller]"
13,tt0105643,Troll 2,A vacationing family discovers that the entire...,"[Comedy, Fantasy, Horror]"
14,tt0046359,Stalag 17,After two Americans are killed while escaping ...,"[Comedy, Drama, War]"
15,tt0064155,Charro!,Vince Hackett's gang steals a prized victory c...,"[Western, Add content advisory]"
16,tt0073705,Shivers,The residents of a suburban high-rise apartmen...,"[Horror, Sci-Fi]"
17,tt0040724,Red River,"Dunson leads a cattle drive, the culmination o...","[Drama, Western]"
18,tt3375370,The Gunfighter,"In the tradition of classic westerns, a narrat...","[Short, Comedy, Western]"
19,tt0061955,The Bride Wore Black,Julie Kohler is prevented from suicide by her ...,"[Crime, Drama, Mystery]"
20,tt0368222,Romance & Cigarettes,This down-and-dirty musical set in the world o...,"[Comedy, Musical, Romance]"
21,tt0052724,Day of the Outlaw,Blaise Starrett is a rancher at odds with home...,"[Drama, Western, Add content advisory]"
22,tt0077288,La Cage aux Folles,The manager of a Saint-Tropez nightclub featur...,[Comedy]
23,tt0058333,The Masque of the Red Death,A European prince terrorizes the local peasant...,"[Drama, Horror]"
24,tt0082527,X-Ray,"While receiving a routine check-up, a woman fi...","[Horror, Thriller]"

In [8]:
dataframe.to_csv('test_data.csv')